
import CrashLogComponent from '../components/CrashLogComponent';


export default function Home() {

  return (
    <main className="flex min-h-screen flex-col items-center p-24">


      <div className="container flex flex-col items-center justify-center mx-auto mt-10">
        <h1 className="text-3xl lg:text-5xl md:text-4xl">Skyrim Online Crash Log Reader</h1>
        <p>Version 1.0</p>
      </div>
      

      <div className="container flex flex-col items-center justify-center mx-auto mt-20">
        <p>
          This program attempts to decipher your Skyrim crash log to find the culprit behind the crash.</p>
          <p>Supports Crash Logs generated by 
            <a href="https://www.nexusmods.com/skyrimspecialedition/mods/59818"> Crash Logger SSE AE VR</a>
        </p>
        <p className="mt-4">
          Paste your Crash Log in the field below, then press 'Generate Report'
        </p>
        <CrashLogComponent />
      </div>

      <div className="container flex flex-col items-center justify-center mx-auto mt-20">
        <h4 className="text-3xl">Contact</h4>
        <p>
          You can contact the author of this application
        </p>
      </div>
    
    </main>
  )
}
