
import CrashLogComponent from '../components/CrashLogComponent';

export const metadata = {
  title: 'Skyrim Crash Decoder',
  description: 'Reads and analyzes your Skyrim Crash Log',
}


export default function Home() {
  

  return (
    <main className="flex min-h-screen flex-col items-center p-24">


      <div className="container flex flex-col items-center justify-center mx-auto mt-4">
        <h1 className="text-3xl lg:text-5xl md:text-4xl"><span className="wwwSpan">www.</span> Skyrim Crash Decoder <span className="wwwSpan">.com</span></h1>
        <p>Version 1.0</p>
      </div>
      

      <div className="container flex flex-col items-center justify-center mx-auto mt-10 w-4/5 lg:w-4/5">
        <p>This web app provides assistance for deciphering your Skyrim Crash Log.</p>
          <p>Supports Crash Logs generated by 
            <a href="https://www.nexusmods.com/skyrimspecialedition/mods/59818"> Crash Logger SSE AE VR</a>.
        </p>
        <p className="mt-4">
          Paste your Crash Log in the field below, then press 'Generate Report'
        </p>
        <CrashLogComponent />
      </div>

      <div className="container flex flex-col items-center justify-center mx-auto mt-20">
        <h4 className="text-3xl mt-3">Contact</h4>
        <p className="mt-3 mb-3">
          If you want to contact the author of this application, you can find me from <a href="https://www.nexusmods.com/users/169060728">Nexusmods</a>.
        </p>
        <img src="https://i.imgur.com/MFyo6QH.png"></img>
      </div>
    
    </main>
  )
}
